version: '3.5'

services:

  service-health-dashboard:
    container_name: service-health-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - '/usr/src/app/service-health-dashboard'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development